[package]
name = "OpenTankTactics"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
poem = "3.0.4"
serde = "1.0.209"
serde_json = "1.0.127"
sqlx = {version = "0.8.1", features = ["runtime-tokio", "postgres"]}